import asyncio
import ipaddress
import json
import os

# The decky plugin module is located at decky-loader/plugin
# For easy intellisense checkout the decky-loader code repo
# and add the `decky-loader/plugin/imports` path to `python.analysis.extraPaths` in `.vscode/settings.json`
import decky

SETTINGS_PATH = os.path.join(decky.DECKY_PLUGIN_SETTINGS_DIR, "settings.json")

# Applied by systemd-sysctl early at boot, before the plugin loader starts.
SYSCTL_CONFIG_PATH = "/etc/sysctl.d/99-decky-ipv6.conf"
SYSCTL_IPV6_CONF_DIR = "/proc/sys/net/ipv6/conf"
IF_INET6_PATH = "/proc/net/if_inet6"

NMCLI = "/usr/bin/nmcli"
IP = "/usr/bin/ip"
SYSCTL = "/usr/bin/sysctl"

# None means the plugin does not manage IPv6 and system defaults apply.
MODES = ("enabled", "disabled", "ipv6_only", None)

# Loopback keeps IPv6 so local services bound to ::1 do not break.
KEEP_ENABLED_INTERFACES = ("lo",)

# Device types whose IPv4 is turned off in IPv6-only mode.
IPV6_ONLY_DEVICE_TYPES = ("wifi", "ethernet")

# SteamOS and NetworkManager may revert these settings (system updates,
# resume, joining another Wi-Fi network), so the selected mode is re-asserted
# at this interval.
ENFORCE_INTERVAL_SECONDS = 5

SYSCTL_CONFIG_HEADER = "# Generated by decky-ipv6, removed when the plugin is set to system default.\n"


def _sysctl_config(disabled: bool) -> str:
    value = "1" if disabled else "0"
    content = SYSCTL_CONFIG_HEADER
    content += f"net.ipv6.conf.all.disable_ipv6 = {value}\n"
    content += f"net.ipv6.conf.default.disable_ipv6 = {value}\n"
    for name in KEEP_ENABLED_INTERFACES:
        content += f"net.ipv6.conf.{name}.disable_ipv6 = 0\n"
    return content


def _write_sysctl(name: str, value: str) -> bool:
    path = os.path.join(SYSCTL_IPV6_CONF_DIR, name, "disable_ipv6")
    try:
        with open(path, "r") as f:
            if f.read().strip() == value:
                return False
        with open(path, "w") as f:
            f.write(value)
        return True
    except OSError as e:
        decky.logger.error(f"Failed to write {path}: {e}")
        return False


def _interfaces() -> list[str]:
    try:
        return [
            name for name in os.listdir(SYSCTL_IPV6_CONF_DIR)
            if name not in ("all", "default")
        ]
    except OSError:
        return []


def _apply_disable_ipv6(disabled: bool) -> None:
    value = "1" if disabled else "0"
    changed = []
    for name in ["all", "default", *_interfaces()]:
        target = "0" if name in KEEP_ENABLED_INTERFACES else value
        if _write_sysctl(name, target):
            changed.append(name)
    if changed:
        decky.logger.info(f"Set disable_ipv6={value} on: {', '.join(changed)}")


def _global_ipv6_addresses() -> list[dict]:
    # /proc/net/if_inet6 columns: address, ifindex, prefix len, scope, flags, ifname
    addresses = []
    try:
        with open(IF_INET6_PATH, "r") as f:
            for line in f:
                fields = line.split()
                if len(fields) != 6 or fields[3] != "00":
                    continue
                addresses.append({
                    "interface": fields[5],
                    "address": str(ipaddress.IPv6Address(bytes.fromhex(fields[0]))),
                    "prefix": int(fields[2], 16),
                })
    except OSError:
        pass
    return addresses


async def _run(*args: str) -> tuple[int, str]:
    # Decky's bundled runtime sets LD_LIBRARY_PATH, which breaks system binaries.
    env = dict(os.environ)
    env.pop("LD_LIBRARY_PATH", None)
    try:
        proc = await asyncio.create_subprocess_exec(
            *args, env=env,
            stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE,
        )
        stdout, stderr = await proc.communicate()
    except OSError as e:
        decky.logger.error(f"Failed to run {args[0]}: {e}")
        return 1, ""
    if proc.returncode != 0:
        decky.logger.error(f"{' '.join(args)} failed ({proc.returncode}): {stderr.decode().strip()}")
    return proc.returncode, stdout.decode()


async def _global_ipv4_addresses() -> list[dict]:
    # e.g. "3: wlan0    inet 192.168.1.5/24 brd 192.168.1.255 scope global dynamic wlan0 ..."
    rc, out = await _run(IP, "-4", "-o", "addr", "show", "scope", "global")
    if rc != 0:
        return []
    addresses = []
    for line in out.splitlines():
        fields = line.split()
        if len(fields) < 4 or fields[2] != "inet":
            continue
        address, _, prefix = fields[3].partition("/")
        addresses.append({"interface": fields[1], "address": address, "prefix": int(prefix or 32)})
    return addresses


async def _connected_devices() -> list[str]:
    rc, out = await _run(NMCLI, "-t", "-f", "DEVICE,TYPE,STATE", "device")
    if rc != 0:
        return []
    devices = []
    for line in out.splitlines():
        fields = line.split(":")
        if len(fields) == 3 and fields[1] in IPV6_ONLY_DEVICE_TYPES and fields[2].startswith("connected"):
            devices.append(fields[0])
    return devices


async def _has_ipv4(device: str) -> bool:
    rc, out = await _run(NMCLI, "-g", "IP4.ADDRESS", "device", "show", device)
    return rc == 0 and out.strip() != ""


async def _disable_ipv4() -> None:
    # `device modify` changes only the active connection, not the saved
    # profile, so nothing needs restoring if the plugin disappears.
    for device in await _connected_devices():
        if await _has_ipv4(device):
            decky.logger.info(f"Disabling IPv4 on {device}")
            await _run(NMCLI, "device", "modify", device, "ipv4.method", "disabled")


async def _restore_ipv4() -> None:
    # `device reapply` resets the active connection to its saved profile.
    for device in await _connected_devices():
        if not await _has_ipv4(device):
            decky.logger.info(f"Restoring IPv4 on {device}")
            await _run(NMCLI, "device", "reapply", device)


class Plugin:
    mode: str | None = None
    enforce_task: asyncio.Task | None = None
    lock = asyncio.Lock()

    def _load_mode(self) -> str | None:
        try:
            with open(SETTINGS_PATH, "r") as f:
                mode = json.load(f).get("mode")
        except (OSError, ValueError):
            return None
        return mode if mode in MODES else None

    def _save_mode(self, mode: str | None) -> None:
        os.makedirs(os.path.dirname(SETTINGS_PATH), exist_ok=True)
        with open(SETTINGS_PATH, "w") as f:
            json.dump({"mode": mode}, f)

    def _write_sysctl_config(self) -> None:
        if self.mode is None:
            if os.path.exists(SYSCTL_CONFIG_PATH):
                os.remove(SYSCTL_CONFIG_PATH)
            return
        content = _sysctl_config(self.mode == "disabled")
        try:
            with open(SYSCTL_CONFIG_PATH, "r") as f:
                if f.read() == content:
                    return
        except OSError:
            pass
        os.makedirs(os.path.dirname(SYSCTL_CONFIG_PATH), exist_ok=True)
        with open(SYSCTL_CONFIG_PATH, "w") as f:
            f.write(content)

    async def _enforce(self) -> None:
        if self.mode is None:
            return
        self._write_sysctl_config()
        _apply_disable_ipv6(self.mode == "disabled")
        if self.mode == "ipv6_only":
            await _disable_ipv4()

    async def _enforce_loop(self):
        while True:
            try:
                async with self.lock:
                    await self._enforce()
            except Exception as e:
                decky.logger.error(f"Enforcing mode {self.mode} failed: {e}")
            await asyncio.sleep(ENFORCE_INTERVAL_SECONDS)

    async def get_status(self) -> dict:
        try:
            with open(os.path.join(SYSCTL_IPV6_CONF_DIR, "all", "disable_ipv6"), "r") as f:
                ipv6_disabled = f.read().strip() == "1"
        except OSError:
            ipv6_disabled = False
        return {
            "mode": self.mode,
            "ipv6_enabled": not ipv6_disabled,
            "ipv6_addresses": _global_ipv6_addresses(),
            "ipv4_addresses": await _global_ipv4_addresses(),
        }

    async def set_mode(self, mode: str | None) -> dict:
        if mode not in MODES:
            raise ValueError(f"Invalid mode: {mode}")
        async with self.lock:
            decky.logger.info(f"Setting mode {self.mode} -> {mode}")
            previous = self.mode
            self.mode = mode
            self._save_mode(mode)
            if previous == "ipv6_only" and mode != "ipv6_only":
                await _restore_ipv4()
            if mode is None:
                self._write_sysctl_config()
                # Reset to the kernel default, then let the system's own
                # sysctl.d configuration take over again.
                _apply_disable_ipv6(False)
                await _run(SYSCTL, "--system")
            else:
                await self._enforce()
        return await self.get_status()

    async def _main(self):
        self.mode = self._load_mode()
        decky.logger.info(f"Loaded mode {self.mode}")
        self.enforce_task = asyncio.get_event_loop().create_task(self._enforce_loop())

    async def _unload(self):
        if self.enforce_task is not None:
            self.enforce_task.cancel()
            self.enforce_task = None

    async def _uninstall(self):
        if self.mode is not None:
            decky.logger.info("Uninstalling, restoring system defaults")
            await self.set_mode(None)

    async def _migration(self):
        pass
