name: Create release on tags

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/1.build_plugin.yml
    secrets: inherit

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: plugin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: "*.zip"
          fail_on_unmatched_files: true
